const data={
    product:[
        {
        _id: '1',
        name:'Nike slim shirt',
        category:'Shirts',
        image:'/images/02.jpg',
        price:'120',
        brand:'Nike',
        rating:4.5,
        numReview:10,
        description:'high quality product',
        },
        {
        _id: '2',
        name:'test slim shirt',
        category:'Shirts',
        image:'/images/02.jpg',
        price:'120',
        brand:'Nike',
        rating:4.5,
        numReview:10,
        description:'high quality product',
        },
        {
        _id: '3',
        name:'Nike slim shirt',
        category:'Shirts',
        image:'/images/02.jpg',
        price:'120',
        brand:'Nike',
        rating:4.5,
        numReview:10,
        description:'high quality product',
        },
        {
        _id: '4',
        name:'Nike slim shirt',
        category:'Shirts',
        image:'/images/02.jpg',
        price:'120',
        brand:'Nike',
        rating:4.5,
        numReview:10,
        description:'high quality product',
        },
        {
        _id: '5',
        name:'Nike slim shirt',
        category:'Shirts',
        image:'/images/02.jpg',
        price:'120',
        brand:'Nike',
        rating:4.5,
        numReview:10,
        description:'high quality product',
        },
        {
        _id: '6',
        name:'Nike slim shirt',
        category:'Shirts',
        image:'/images/02.jpg',
        price:'120',
        brand:'Nike',
        rating:4.5,
        numReview:10,
        description:'high quality product',
        },
        {
        _id: '7',
        name:'Nike slim shirt',
        category:'Shirts',
        image:'/images/02.jpg',
        price:'120',
        brand:'Nike',
        rating:4.5,
        numReview:10,
        description:'high quality product',
        }
    ]
}
export default data;